## Загрузка файла CSV с ID в качестве индекса

In [14]:
import pandas as pd

df = pd.read_csv('data/auto.csv', index_col='ID')

df.head()

       CarNumber  Make_n_model  Refund   Fines  History
ID
0   Y163O8161RUS    Ford Focus     2.0  3200.0      NaN
1    E432XX77RUS  Toyota Camry     1.0  6500.0      NaN
2    7184TT36RUS    Ford Focus     1.0  2100.0      NaN
3   X582HE161RUS    Ford Focus     2.0  2000.0      NaN
4   E34877152RUS    Ford Focus     2.0  6100.0      NaN

## Подсчет наблюдений и удаление дубликатов

In [15]:
print(f'Количество непустых наблюдейний в каждом столбце:\n{df.count()}')

df = df.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last')
print(f'\nКоличество непустых наблюдений в каждом столбце после удаления дубликатов:\n{df.count()}')

Количество непустых наблюдейний в каждом столбце:
CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

Количество непустых наблюдений в каждом столбце после удаления дубликатов:
CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## Работа с пропущенными значениями - удаление столбцов со многими NA

In [16]:
print(f'Отсутствующие значения до чистки:\n{df.isna().sum()}')
df = df.dropna(axis=1, thresh=len(df)-500)
print(f'\nОтсутствующие значения после чистки:\n{df.isna().sum()}')

Отсутствующие значения до чистки:
CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

Отсутствующие значения после чистки:
CarNumber        0
Make_n_model     0
Refund          12
Fines           60
dtype: int64

## Заполнение пропущенных значений в столбцах Refund и Fines

In [17]:
df['Refund'] = df['Refund'].ffill()
print(f'После препроцессинга Refund:\n{df.isna().sum()}')

df['Fines'] = df['Fines'].fillna(df['Fines'].mean())
print(f'\nПосле препроцессинга Fines:\n{df.isna().sum()}')

После препроцессинга Refund:
CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

После препроцессинга Fines:
CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

## Разделение Make_n_model на столбцы Make и Model

In [18]:
df['Make'] = df['Make_n_model'].apply(lambda x: x.split()[0] if pd.notna(x) else None)
df['Model'] = df['Make_n_model'].apply(lambda x: ' '.join(x.split()[1:]) if pd.notna(x) and len(x.split()) > 1 else None)
df = df.drop(columns=['Make_n_model'])
df.head(5)

       CarNumber  Refund   Fines    Make  Model
ID
0   Y163O8161RUS     2.0  3200.0    Ford  Focus
1    E432XX77RUS     1.0  6500.0  Toyota  Camry
2    7184TT36RUS     1.0  2100.0    Ford  Focus
3   X582HE161RUS     2.0  2000.0    Ford  Focus
5   92918M178RUS     1.0  5700.0    Ford  Focus

## Сохранение в файл JSON

In [19]:
df.to_json('data/auto.json', orient='records', indent=4)