## Загрузка JSON и установка индекса

In [61]:
import pandas as pd

df = pd.read_json('data/auto.json', orient='records')
df = df.set_index('CarNumber')
df.head(5)

              Refund   Fines    Make  Model
CarNumber
Y163O8161RUS       2  3200.0    Ford  Focus
E432XX77RUS        1  6500.0  Toyota  Camry
7184TT36RUS        1  2100.0    Ford  Focus
X582HE161RUS       2  2000.0    Ford  Focus
92918M178RUS       1  5700.0    Ford  Focus

## Выборка - штрафы больше 2100

In [62]:
f_over2100 = df[df['Fines'] > 2100]
f_over2100

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

## Выборка - штрафы > 2100 и возврат = 2

In [63]:
f_over2100[f_over2100['Refund'] == 2]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

## Выборка - модели Фокус и Королла

In [64]:
models=['Focus','Corolla']
df.loc[df['Model'].isin(models)]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

## Выборка - конкретные номера автомобилей

In [65]:
cnum_list = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df[df.index.isin(cnum_list)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## Агрегация - медианные штрафы по маркам

In [66]:
df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

## Агрегация - медианные штрафы по маркам и моделям

In [67]:
df.groupby(['Make','Model'])['Fines'].median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

## Агрегация - подсчет количества штрафов по маркам и моделям

In [68]:
df.groupby(['Make','Model']).agg('Fines').count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

## Агрегация - минимальные и максимальные штрафы по маркам и моделям

In [69]:
df.groupby(['Make','Model'])['Fines'].agg(['min','max'])

                       min            max
Make       Model
Ford       Focus     100.0  180000.000000
           Mondeo   1100.0   46200.000000
Skoda      Octavia   300.0  145000.000000
Toyota     Camry     500.0   22400.000000
           Corolla   900.0   34300.000000
Volkswagen Golf      200.0  168000.000000
           Jetta     500.0   46000.000000
           Passat    100.0   29700.000000
           Touareg   500.0    8594.586466

## Агрегация - стандартное отклонение штрафов по маркам и моделям

In [70]:
df.groupby(['Make','Model'])['Fines'].std()

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## Агрегация номеров автомобилей по количеству штрафов

In [71]:
carnum_sort = df.groupby(df.index)['Fines'].count().sort_values(ascending=False)
carnum_sort

CarNumber
92928M178RUS    4
Y7689C197RUS    4
7788KT197RUS    4
X015HY197RUS    3
7830C8197RUS    3
               ..
H837YK197RUS    1
H618YC38RUS     1
8451M7154RUS    1
8513XX154RUS    1
8440XX154RUS    1
Name: Fines, Length: 531, dtype: int64

## Топ-1 по количеству штрафов

In [72]:
df.loc[carnum_sort.index[0]]

              Refund        Fines  Make  Model
CarNumber
92928M178RUS       1  8594.586466  Ford  Focus
92928M178RUS       1   600.000000  Ford  Focus
92928M178RUS       1  1200.000000  Ford  Focus
92928M178RUS       2  3000.000000  Ford  Focus

## Номера автомобилей, сгруппированные по сумме штрафов

In [73]:
carnum_f_sort = df.groupby(df.index)['Fines'].sum().sort_values(ascending=False)
carnum_f_sort

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y195O8161RUS       100.0
C58078163RUS       100.0
K326T8197RUS       100.0
K376HE161RUS       100.0
83218C154RUS       100.0
Name: Fines, Length: 531, dtype: float64

## Выбор топ-1 номера автомобиля по сумме штрафов

In [74]:
df.loc[carnum_f_sort.index[0]]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

## Проверка номеров автомобилей, связанных с разными моделями

In [75]:
diff_models = df.groupby(df.index)['Model'].nunique(dropna=False)
df[df.index.isin(diff_models[diff_models > 1].index)]

              Refund   Fines        Make    Model
CarNumber
E316EH197RUS       1  1300.0  Volkswagen      NaN
E316EH197RUS       1  1300.0  Volkswagen  Touareg